# This workflow performs chapter quality (known issues) and code quality checks upon new commits and PRs.

name: Check new commits and PRs

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1 # 0 if you want to push to repo

      - name: Touch requirements.txt for pip caching
        run: touch requirements.txt

      - name: Python set up
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Check of chapters for known issues
        run: python3 scripts/check_chapters.py

      - name: Check pre-commit tests
        uses: pre-commit/action@v3.0.1
