---

name: "Kreu eldonon"
run-name: "Kreu eldonon ${{ inputs.version_number }}"

on:
  workflow_dispatch:
    inputs:

      version_number:
        required: true
        default: "vX.Y.Z"
        description: |
          Versia numero

      version_text:
        required: true
        default: ""
        description: |
          Priskribo de la eldono

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: ln -s python-requirements.txt requirements.txt

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: wget --quiet "${URL}" -O hpmor-prev.html
        env:
          URL: https://github.com/${{ github.repository }}/releases/download/LaboroEnProgreso/hpmor.html

      - uses: abbbi/github-actions-tune@v1

      - run: sh scripts/install_requirements.sh > /dev/null
      - run: sh scripts/make_pdfs.sh > /dev/null
      - run: sh scripts/make_ebooks.sh

      - run: diff -u -s hpmor-prev.html hpmor.html | tee hpmor-html-diff.log
      - run: rm hpmor-prev.html

      - uses: actions/upload-artifact@v4
        with:
          name: bitlibrojn
          retention-days: 14
          path: |
            ./hpmor-html-diff.log
            ./hpmor.epub
            ./hpmor.mobi
            ./hpmor.fb2
            ./hpmor.html
            ./hpmor*.pdf

      - if: github.ref_name == 'esperantigo/unua-provo'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ inputs.version_number }}"
          body: "${{ inputs.version_text }}"
          prerelease: false
          target_commitish: ${{ github.sha }}
          files: |
            ./hpmor-html-diff.log
            ./hpmor.epub
            ./hpmor.mobi
            ./hpmor.fb2
            ./hpmor.html
            ./hpmor*.pdf
